language: cpp
before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get -y install gcc-7 g++-7 libboost-test-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 1
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 1
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T join_server-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uasvgit:$BINTRAY_API_KEY "https://api.bintray.com/content/savaorg/otuscpp/homework/$TRAVIS_BUILD_NUMBER/join_server-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
